/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItem } from "./components/xy-editor/components/xy-button-menu/xy-button-menu";
import { Editor } from "@tiptap/core";
export { MenuItem } from "./components/xy-editor/components/xy-button-menu/xy-button-menu";
export { Editor } from "@tiptap/core";
export namespace Components {
    interface XyButtonMenu {
        "data": MenuItem;
    }
    interface XyEditor {
        "bubbleBar": string[];
        "content": string;
        "excludeBar": string[];
        "extensions": any[];
        "lange": string;
        "menuBar": string[];
        "placeholder": string;
        "theme": string;
    }
    interface XyIcon {
        "height"?: string | number;
        "name"?: string;
        "width"?: string | number;
    }
    interface XyMenuBar {
        "editor"?: Editor;
        "menuBar"?: any;
    }
}
declare global {
    interface HTMLXyButtonMenuElement extends Components.XyButtonMenu, HTMLStencilElement {
    }
    var HTMLXyButtonMenuElement: {
        prototype: HTMLXyButtonMenuElement;
        new (): HTMLXyButtonMenuElement;
    };
    interface HTMLXyEditorElement extends Components.XyEditor, HTMLStencilElement {
    }
    var HTMLXyEditorElement: {
        prototype: HTMLXyEditorElement;
        new (): HTMLXyEditorElement;
    };
    interface HTMLXyIconElement extends Components.XyIcon, HTMLStencilElement {
    }
    var HTMLXyIconElement: {
        prototype: HTMLXyIconElement;
        new (): HTMLXyIconElement;
    };
    interface HTMLXyMenuBarElement extends Components.XyMenuBar, HTMLStencilElement {
    }
    var HTMLXyMenuBarElement: {
        prototype: HTMLXyMenuBarElement;
        new (): HTMLXyMenuBarElement;
    };
    interface HTMLElementTagNameMap {
        "xy-button-menu": HTMLXyButtonMenuElement;
        "xy-editor": HTMLXyEditorElement;
        "xy-icon": HTMLXyIconElement;
        "xy-menu-bar": HTMLXyMenuBarElement;
    }
}
declare namespace LocalJSX {
    interface XyButtonMenu {
        "data"?: MenuItem;
    }
    interface XyEditor {
        "bubbleBar"?: string[];
        "content"?: string;
        "excludeBar"?: string[];
        "extensions"?: any[];
        "lange"?: string;
        "menuBar"?: string[];
        "placeholder"?: string;
        "theme"?: string;
    }
    interface XyIcon {
        "height"?: string | number;
        "name"?: string;
        "width"?: string | number;
    }
    interface XyMenuBar {
        "editor"?: Editor;
        "menuBar"?: any;
    }
    interface IntrinsicElements {
        "xy-button-menu": XyButtonMenu;
        "xy-editor": XyEditor;
        "xy-icon": XyIcon;
        "xy-menu-bar": XyMenuBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xy-button-menu": LocalJSX.XyButtonMenu & JSXBase.HTMLAttributes<HTMLXyButtonMenuElement>;
            "xy-editor": LocalJSX.XyEditor & JSXBase.HTMLAttributes<HTMLXyEditorElement>;
            "xy-icon": LocalJSX.XyIcon & JSXBase.HTMLAttributes<HTMLXyIconElement>;
            "xy-menu-bar": LocalJSX.XyMenuBar & JSXBase.HTMLAttributes<HTMLXyMenuBarElement>;
        }
    }
}
